var app = getApp()

module.exports = {
  areaCode: [
    [
      { "aleph": "afh", "continent": 1, "id": "+93", "length": 9, "pinyin": "afuhan", "value": "阿富汗 0093" },
      { "aleph": "asbj", "continent": 1, "id": "+994", "length": 9, "pinyin": "asaibaijiang", "value": "阿塞拜疆 0994" },
      { "aleph": "am", "continent": 1, "id": "+968", "length": 9, "pinyin": "aman", "value": "阿曼 0968" },
      { "aleph": "alq", "continent": 1, "id": "+971", "length": 9, "pinyin": "alianqiu", "value": "阿联酋 0971" },
      { "aleph": "agl", "continent": 2, "id": "1264", "length": 9, "pinyin": "anguila", "value": "安圭拉 1264" },
      { "aleph": "atghbbd", "continent": 2, "id": "1268", "length": 9, "pinyin": "antiguahebabuda", "value": "安提瓜和巴布达 1268" },
      { "aleph": "alb", "continent": 2, "id": "+297", "length": 9, "pinyin": "aluba", "value": "阿鲁巴 0297" },
      { "aleph": "agt", "continent": 2, "id": "+54", "length": 9, "pinyin": "agenting", "value": "阿根廷 0054" },
      { "aleph": "aebny", "continent": 3, "id": "+355", "length": 9, "pinyin": "aerbaniya", "value": "阿尔巴尼亚 0355" },
      { "aleph": "adl", "continent": 3, "id": "+43", "length": 9, "pinyin": "aodili", "value": "奥地利 0043" },
      { "aleph": "ael", "continent": 3, "id": "+353", "length": 9, "pinyin": "aierlan", "value": "爱尔兰 0353" },
      { "aleph": "ade", "continent": 3, "id": "+376", "length": 9, "pinyin": "andaoer", "value": "安道尔 0376" },
      { "aleph": "asny", "continent": 3, "id": "+372", "length": 9, "pinyin": "aishaniya", "value": "爱沙尼亚 0372" },
      { "aleph": "adly", "continent": 4, "id": "+61", "length": 9, "pinyin": "aodaliya", "value": "澳大利亚 0061" },
      { "aleph": "agl", "continent": 5, "id": "+244", "length": 9, "pinyin": "angela", "value": "安哥拉 0244" },
      { "aleph": "assd", "continent": 5, "id": "+247", "length": 9, "pinyin": "asensongdao", "value": "阿森松岛 0247" },
      { "aleph": "aj", "continent": 5, "id": "+20", "length": 9, "pinyin": "aiji", "value": "埃及 0020" },
      { "aleph": "aseby", "continent": 5, "id": "+251", "length": 9, "pinyin": "aisaiebiya", "value": "埃塞俄比亚 0251" },
      { "aleph": "aejly", "continent": 5, "id": "+213", "length": 9, "pinyin": "aerjiliya", "value": "阿尔及利亚 0213" },
    ],
    [
      { "aleph": "bl", "continent": 1, "id": "+973", "length": 9, "pinyin": "balin", "value": "巴林 0973" },
      { "aleph": "bd", "continent": 1, "id": "+975", "length": 9, "pinyin": "budan", "value": "不丹 0975" },
      { "aleph": "bjst", "continent": 1, "id": "+92", "length": 9, "pinyin": "bajisitan", "value": "巴基斯坦 0092" },
      { "aleph": "blst", "continent": 1, "id": "+970", "length": 9, "pinyin": "balesitan", "value": "巴勒斯坦 0970" },
      { "aleph": "bx", "continent": 2, "id": "+55", "length": 11, "pinyin": "baxi", "value": "巴西 0055" },
      { "aleph": "bhm", "continent": 2, "id": "1242", "length": 9, "pinyin": "bahama", "value": "巴哈马 1242" },
      { "aleph": "bbds", "continent": 2, "id": "1246", "length": 9, "pinyin": "babaduosi", "value": "巴巴多斯 1246" },
      { "aleph": "blz", "continent": 2, "id": "+501", "length": 9, "pinyin": "bolizi", "value": "伯利兹 0501" },
      { "aleph": "bmdqd", "continent": 2, "id": "1441", "length": 9, "pinyin": "baimudaqundao", "value": "百慕大群岛 1441" },
      { "aleph": "bnm", "continent": 2, "id": "+507", "length": 9, "pinyin": "banama", "value": "巴拿马 0507" },
      { "aleph": "bdlg", "continent": 2, "id": "1787", "length": 9, "pinyin": "boduolige", "value": "波多黎各 1787" },
      { "aleph": "blwy", "continent": 2, "id": "+591", "length": 9, "pinyin": "boliweiya", "value": "玻利维亚 0591" },
      { "aleph": "blg", "continent": 2, "id": "+595", "length": 9, "pinyin": "balagui", "value": "巴拉圭 0595" },
      { "aleph": "bls", "continent": 3, "id": "+32", "length": 9, "pinyin": "bilishi", "value": "比利时 0032" },
      { "aleph": "bsnyhhsgwn", "continent": 3, "id": "+387", "length": 9, "pinyin": "bosiniyaheheisaigeweinei", "value": "波斯尼亚和黑塞哥维那 0387" },
      { "aleph": "bjly", "continent": 3, "id": "+359", "length": 9, "pinyin": "baojialiya", "value": "保加利亚 0359" },
      { "aleph": "bd", "continent": 3, "id": "+354", "length": 9, "pinyin": "bingdao", "value": "冰岛 0354" },
      { "aleph": "bl", "continent": 3, "id": "+48", "length": 9, "pinyin": "bolan", "value": "波兰 0048" },
      { "aleph": "bels", "continent": 3, "id": "+375", "length": 9, "pinyin": "baieluosi", "value": "白俄罗斯 0375" },
      { "aleph": "bbyxjny", "continent": 4, "id": "+675", "length": 9, "pinyin": "babuyaxinjineiya", "value": "巴布亚新几内亚 0675" },
      { "aleph": "bn", "continent": 5, "id": "+229", "length": 9, "pinyin": "beining", "value": "贝宁 0229" },
      { "aleph": "bcwn", "continent": 5, "id": "+267", "length": 9, "pinyin": "bociwana", "value": "博茨瓦纳 0267" },
      { "aleph": "bjnfs", "continent": 5, "id": "+226", "length": 9, "pinyin": "bujinafasuo", "value": "布基纳法索 0226" },
      { "aleph": "bld", "continent": 5, "id": "+257", "length": 9, "pinyin": "bulongdi", "value": "布隆迪 0257" },
    ],
    [
      { "aleph": "cx", "continent": 1, "id": "+850", "length": 9, "pinyin": "chaoxian", "value": "朝鲜 0850" },
      { "aleph": "cdjny", "continent": 5, "id": "+240", "length": 9, "pinyin": "chidaojineiya", "value": "赤道几内亚 0240" },
    ],
    [
      { "aleph": "ddw", "continent": 1, "id": "+670", "length": 9, "pinyin": "dongdiwen", "value": "东帝汶 0670" },
      { "aleph": "dmnk", "continent": 2, "id": "1767", "length": 9, "pinyin": "duominike", "value": "多米尼克 1767" },
      { "aleph": "dmnj", "continent": 2, "id": "1849", "length": 9, "pinyin": "duominijia", "value": "多米尼加 1849" },
      { "aleph": "dm", "continent": 3, "id": "+45", "length": 8, "pinyin": "danmai", "value": "丹麦 0045" },
      { "aleph": "dg", "continent": 3, "id": "+49", "length": 11, "pinyin": "deguo", "value": "德国 0049" },
      { "aleph": "dg", "continent": 5, "id": "+228", "length": 9, "pinyin": "duoge", "value": "多哥 0228" },
    ],
    [
      { "aleph": "egde", "continent": 2, "id": "+593", "length": 9, "pinyin": "eguaduoer", "value": "厄瓜多尔 0593" },
      { "aleph": "els", "continent": 3, "id": "+7", "length": 10, "pinyin": "eluosi", "value": "俄罗斯 0007" },
      { "aleph": "eltly", "continent": 5, "id": "+291", "length": 9, "pinyin": "eliteliya", "value": "厄立特里亚 0291" },
    ],
    [
      { "aleph": "flb", "continent": 1, "id": "+63", "length": 10, "pinyin": "feilvbin", "value": "菲律宾 0063" },
      { "aleph": "fsgyn", "continent": 2, "id": "+594", "length": 9, "pinyin": "fashuguiyanei", "value": "法属圭亚那 0594" },
      { "aleph": "flqd", "continent": 3, "id": "+298", "length": 9, "pinyin": "faluoqundao", "value": "法罗群岛 0298" },
      { "aleph": "fl", "continent": 3, "id": "+358", "length": 9, "pinyin": "fenlan", "value": "芬兰 0358" },
      { "aleph": "fg", "continent": 3, "id": "+33", "length": 9, "pinyin": "faguo", "value": "法国 0033" },
      { "aleph": "fdg", "continent": 3, "id": "+396", "length": 9, "pinyin": "fandigang", "value": "梵蒂冈 0396" },
      { "aleph": "fjqd", "continent": 4, "id": "+679", "length": 9, "pinyin": "feijiqundao", "value": "斐济群岛 0679" },
      { "aleph": "fsblnxy", "continent": 4, "id": "+689", "length": 9, "pinyin": "fashubolinixiya", "value": "法属波利尼西亚 0689" },
      { "aleph": "fdj", "continent": 5, "id": "+238", "length": 9, "pinyin": "fodejiao", "value": "佛得角 0238" },
    ],
    [
      { "aleph": "gljy", "continent": 1, "id": "+995", "length": 9, "pinyin": "gelujiya", "value": "格鲁吉亚 0995" },
      { "aleph": "gsdlj", "continent": 2, "id": "+506", "length": 9, "pinyin": "gesidalijia", "value": "哥斯达黎加 0506" },
      { "aleph": "gb", "continent": 2, "id": "+53", "length": 9, "pinyin": "guba", "value": "古巴 0053" },
      { "aleph": "gll", "continent": 2, "id": "+299", "length": 9, "pinyin": "gelinglan", "value": "格陵兰 0299" },
      { "aleph": "glnd", "continent": 2, "id": "1473", "length": 9, "pinyin": "gelinnada", "value": "格林纳达 1473" },
      { "aleph": "gdlp", "continent": 2, "id": "+590", "length": 9, "pinyin": "guadeluopu", "value": "瓜德罗普 0590" },
      { "aleph": "glby", "continent": 2, "id": "+57", "length": 9, "pinyin": "gelunbiya", "value": "哥伦比亚 0057" },
      { "aleph": "gyn", "continent": 2, "id": "+592", "length": 9, "pinyin": "guiyanei", "value": "圭亚那 0592" },
      { "aleph": "gd", "continent": 4, "id": "1671", "length": 9, "pinyin": "guandao", "value": "关岛 1671" },
      { "aleph": "gby", "continent": 5, "id": "+220", "length": 9, "pinyin": "gangbiya", "value": "冈比亚 0220" },
    ],
    [
      { "aleph": "hg", "continent": 1, "id": "+82", "length": 10, "pinyin": "hanguo", "value": "韩国 0082" },
      { "aleph": "hskst", "continent": 1, "id": "+7", "length": 9, "pinyin": "hasakesitan", "value": "哈萨克斯坦 0007" },
      { "aleph": "hd", "continent": 2, "id": "+509", "length": 9, "pinyin": "haidi", "value": "海地 0509" },
      { "aleph": "hdls", "continent": 2, "id": "+504", "length": 9, "pinyin": "hongdoulasi", "value": "洪都拉斯 0504" },
      { "aleph": "hsadlsqd", "continent": 2, "id": "+599", "length": 9, "pinyin": "heshuandeliesiqundao", "value": "荷属安的列斯群岛 0599" },
      { "aleph": "hs", "continent": 3, "id": "+382", "length": 9, "pinyin": "heishan", "value": "黑山 0382" },
      { "aleph": "hl", "continent": 3, "id": "+31", "length": 9, "pinyin": "helan", "value": "荷兰 0031" },
    ],
    [

    ],
    [
      { "aleph": "jnd", "continent": 0, "id": "+1", "length": 10, "pinyin": "jianada", "value": "加拿大 0001" },
      { "aleph": "jpz", "continent": 1, "id": "+855", "length": 9, "pinyin": "jianpuzhai", "value": "柬埔寨 0855" },
      { "aleph": "jejsst", "continent": 1, "id": "+996", "length": 9, "pinyin": "jierjisisitan", "value": "吉尔吉斯斯坦 0996" },
      { "aleph": "jk", "continent": 3, "id": "+420", "length": 9, "pinyin": "jieke", "value": "捷克 0420" },
      { "aleph": "jlbs", "continent": 4, "id": "+686", "length": 9, "pinyin": "jilibasi", "value": "基里巴斯 0686" },
      { "aleph": "jbt", "continent": 5, "id": "+253", "length": 9, "pinyin": "jibuti", "value": "吉布提 0253" },
      { "aleph": "jp", "continent": 5, "id": "+241", "length": 9, "pinyin": "jiapeng", "value": "加蓬 0241" },
      { "aleph": "jn", "continent": 5, "id": "+233", "length": 9, "pinyin": "jiana", "value": "加纳 0233" },
      { "aleph": "jny", "continent": 5, "id": "+224", "length": 9, "pinyin": "jineiya", "value": "几内亚 0224" },
      { "aleph": "jnybs", "continent": 5, "id": "+245", "length": 9, "pinyin": "jineiyabishao", "value": "几内亚比绍 0245" },
      { "aleph": "jbbw", "continent": 5, "id": "+263", "length": 9, "pinyin": "jinbabuwei", "value": "津巴布韦 0263" }
    ],
    [
      { "aleph": "kwt", "continent": 1, "id": "+965", "length": 9, "pinyin": "keweite", "value": "科威特 0965" },
      { "aleph": "kte", "continent": 1, "id": "+974", "length": 9, "pinyin": "kataer", "value": "卡塔尔 0974" },
      { "aleph": "kmqd", "continent": 2, "id": "1345", "length": 9, "pinyin": "kaimanqundao", "value": "开曼群岛 1345" },
      { "aleph": "kldy", "continent": 3, "id": "+385", "length": 9, "pinyin": "keluodiya", "value": "克罗地亚 0385" },
      { "aleph": "kkqd", "continent": 4, "id": "+682", "length": 9, "pinyin": "kukequndao", "value": "库克群岛 0682" },
      { "aleph": "kml", "continent": 5, "id": "+237", "length": 9, "pinyin": "kamailong", "value": "喀麦隆 0237" },
      { "aleph": "ktdw", "continent": 5, "id": "+225", "length": 9, "pinyin": "ketediwa", "value": "科特迪瓦 0225" },
      { "aleph": "kny", "continent": 5, "id": "+254", "length": 9, "pinyin": "kenniya", "value": "肯尼亚 0254" },
      { "aleph": "kml", "continent": 5, "id": "+269", "length": 9, "pinyin": "kemoluo", "value": "科摩罗 0269" },
    ],
    [
      { "aleph": "lw", "continent": 1, "id": "+856", "length": 9, "pinyin": "laowo", "value": "老挝 0856" },
      { "aleph": "lbn", "continent": 1, "id": "+961", "length": 9, "pinyin": "libanen", "value": "黎巴嫩 0961" },
      { "aleph": "lsb", "continent": 3, "id": "+352", "length": 9, "pinyin": "lusenbao", "value": "卢森堡 0352" },
      { "aleph": "lmny", "continent": 3, "id": "+40", "length": 9, "pinyin": "luomaniya", "value": "罗马尼亚 0040" },
      { "aleph": "lzdsd", "continent": 3, "id": "4175", "length": 9, "pinyin": "liezhidunshideng", "value": "列支敦士登 4175" },
      { "aleph": "ltwy", "continent": 3, "id": "+371", "length": 9, "pinyin": "latuoweiya", "value": "拉脱维亚 0371" },
      { "aleph": "ltw", "continent": 3, "id": "+370", "length": 9, "pinyin": "litaowan", "value": "立陶宛 0370" },
      { "aleph": "lst", "continent": 5, "id": "+266", "length": 9, "pinyin": "laisuotuo", "value": "莱索托 0266" },
      { "aleph": "lbly", "continent": 5, "id": "+231", "length": 9, "pinyin": "libiliya", "value": "利比里亚 0231" },
      { "aleph": "lby", "continent": 5, "id": "+218", "length": 9, "pinyin": "libiya", "value": "利比亚 0218" },
      { "aleph": "lnwd", "continent": 5, "id": "+262", "length": 9, "pinyin": "liuniwangdao", "value": "留尼旺岛 0262" },
      { "aleph": "lwd", "continent": 5, "id": "+250", "length": 9, "pinyin": "luwangda", "value": "卢旺达 0250" },
    ],
    [
      { "aleph": "mlxy", "continent": 0, "id": "+60", "length": 9, "pinyin": "malaixiya", "value": "马来西亚 0060" },
      { "aleph": "mg", "continent": 0, "id": "+1", "length": 10, "pinyin": "meiguo", "value": "美国 0001" },
      { "aleph": "mjl", "continent": 1, "id": "+880", "length": 9, "pinyin": "mengjiala", "value": "孟加拉 0880" },
      { "aleph": "mg", "continent": 1, "id": "+976", "length": 9, "pinyin": "menggu", "value": "蒙古 0976" },
      { "aleph": "medf", "continent": 1, "id": "+960", "length": 9, "pinyin": "maerdaifu", "value": "马尔代夫 0960" },
      { "aleph": "mtnk", "continent": 2, "id": "+596", "length": 9, "pinyin": "matinike", "value": "马提尼克 0596" },
      { "aleph": "mxg", "continent": 2, "id": "+52", "length": 9, "pinyin": "moxige", "value": "墨西哥 0052" },
      { "aleph": "mtslt", "continent": 2, "id": "1664", "length": 9, "pinyin": "mengtesailate", "value": "蒙特塞拉特 1664" },
      { "aleph": "mswejqd", "continent": 2, "id": "1340", "length": 9, "pinyin": "meishuweierjingqundao", "value": "美属维尔京群岛 1340" },
      { "aleph": "ml", "continent": 2, "id": "+51", "length": 9, "pinyin": "milu", "value": "秘鲁 0051" },
      { "aleph": "met", "continent": 3, "id": "+356", "length": 9, "pinyin": "maerta", "value": "马耳他 0356" },
      { "aleph": "mng", "continent": 3, "id": "+377", "length": 9, "pinyin": "monage", "value": "摩纳哥 0377" },
      { "aleph": "mqd", "continent": 3, "id": "+389", "length": 9, "pinyin": "maqidun", "value": "马其顿 0389" },
      { "aleph": "medw", "continent": 3, "id": "+373", "length": 9, "pinyin": "moerduowa", "value": "摩尔多瓦 0373" },
      { "aleph": "mssmy", "continent": 4, "id": "+684", "length": 9, "pinyin": "meishusamoya", "value": "美属萨摩亚 0684" },
      { "aleph": "mklnxy", "continent": 4, "id": "+691", "length": 9, "pinyin": "mikeluonixiya", "value": "密克罗尼西亚 0691" },
      { "aleph": "mseqd", "continent": 4, "id": "+692", "length": 9, "pinyin": "mashaoerqundao", "value": "马绍尔群岛 0692" },
      { "aleph": "mdjsj", "continent": 5, "id": "+261", "length": 9, "pinyin": "madajiasijia", "value": "马达加斯加 0261" },
      { "aleph": "ml", "continent": 5, "id": "+223", "length": 9, "pinyin": "mali", "value": "马里 0223" },
      { "aleph": "mlqs", "continent": 5, "id": "+230", "length": 9, "pinyin": "maoliqiusi", "value": "毛里求斯 0230" },
      { "aleph": "mlg", "continent": 5, "id": "+212", "length": 9, "pinyin": "moluoge", "value": "摩洛哥 0212" },
      { "aleph": "msbk", "continent": 5, "id": "+258", "length": 9, "pinyin": "mosangbike", "value": "莫桑比克 0258" },
      { "aleph": "mltny", "continent": 5, "id": "+222", "length": 9, "pinyin": "maolitaniya", "value": "毛里塔尼亚 0222" },
      { "aleph": "mlw", "continent": 5, "id": "+265", "length": 9, "pinyin": "malawei", "value": "马拉维 0265" },
    ],
    [
      { "aleph": "nbe", "continent": 1, "id": "+977", "length": 9, "pinyin": "niboer", "value": "尼泊尔 0977" },
      { "aleph": "njlg", "continent": 2, "id": "+505", "length": 9, "pinyin": "nijialagua", "value": "尼加拉瓜 0505" },
      { "aleph": "nw", "continent": 3, "id": "+47", "length": 9, "pinyin": "nuowei", "value": "挪威 0047" },
      { "aleph": "nl", "continent": 4, "id": "+674", "length": 9, "pinyin": "naolu", "value": "瑙鲁 0674" },
      { "aleph": "nad", "continent": 4, "id": "+683", "length": 9, "pinyin": "niuaidao", "value": "纽埃岛 0683" },
      { "aleph": "nfkd", "continent": 4, "id": "6723", "length": 9, "pinyin": "nuofukedao", "value": "诺福克岛 6723" },
      { "aleph": "nre", "continent": 5, "id": "+227", "length": 9, "pinyin": "nirier", "value": "尼日尔 0227" },
      { "aleph": "nrly", "continent": 5, "id": "+234", "length": 9, "pinyin": "niriliya", "value": "尼日利亚 0234" },
      { "aleph": "nmby", "continent": 5, "id": "+264", "length": 9, "pinyin": "namibiya", "value": "纳米比亚 0264" },
      { "aleph": "nf", "continent": 5, "id": "+27", "length": 9, "pinyin": "nanfei", "value": "南非 0027" },
      { "aleph": "nsd", "continent": 5, "id": "+211", "length": 9, "pinyin": "nansudan", "value": "南苏丹 0211" },
    ],
    [
    ],
    [
      { "aleph": "pty", "continent": 3, "id": "+351", "length": 9, "pinyin": "putaoya", "value": "葡萄牙 0351" },
      { "aleph": "pl", "continent": 4, "id": "+680", "length": 9, "pinyin": "palao", "value": "帕劳 0680" },
    ],
    [
    ],
    [
      { "aleph": "rb", "continent": 1, "id": "+81", "length": 10, "pinyin": "riben", "value": "日本 0081" },
      { "aleph": "rd", "continent": 3, "id": "+46", "length": 9, "pinyin": "ruidian", "value": "瑞典 0046" },
      { "aleph": "rs", "continent": 3, "id": "+41", "length": 9, "pinyin": "ruishi", "value": "瑞士 0041" },
    ],
    [
      { "aleph": "spls", "continent": 1, "id": "+357", "length": 9, "pinyin": "saipulusi", "value": "塞浦路斯 0357" },
      { "aleph": "stalb", "continent": 1, "id": "+966", "length": 9, "pinyin": "shatealabo", "value": "沙特阿拉伯 0966" },
      { "aleph": "sllk", "continent": 1, "id": "+94", "length": 9, "pinyin": "sililanka", "value": "斯里兰卡 0094" },
      { "aleph": "sewd", "continent": 2, "id": "+503", "length": 9, "pinyin": "saerwaduo", "value": "萨尔瓦多 0503" },
      { "aleph": "swsthglnds", "continent": 2, "id": "1784", "length": 9, "pinyin": "shengwensentehegelinnadingsi", "value": "圣文森特和格林纳丁斯 1784" },
      { "aleph": "slxy", "continent": 2, "id": "1758", "length": 9, "pinyin": "shengluxiya", "value": "圣卢西亚 1758" },
      { "aleph": "sjchnws", "continent": 2, "id": "1869", "length": 9, "pinyin": "shengjiciheniweisi", "value": "圣基茨和尼维斯 1869" },
      { "aleph": "sln", "continent": 2, "id": "+597", "length": 9, "pinyin": "sulinan", "value": "苏里南 0597" },
      { "aleph": "smln", "continent": 3, "id": "+378", "length": 9, "pinyin": "shengmalinuo", "value": "圣马力诺 0378" },
      { "aleph": "sewy", "continent": 3, "id": "+381", "length": 9, "pinyin": "saierweiya", "value": "塞尔维亚 0381" },
      { "aleph": "slwny", "continent": 3, "id": "+386", "length": 9, "pinyin": "siluowenniya", "value": "斯洛文尼亚 0386" },
      { "aleph": "slfk", "continent": 3, "id": "+421", "length": 9, "pinyin": "siluofake", "value": "斯洛伐克 0421" },
      { "aleph": "slmqd", "continent": 4, "id": "+677", "length": 9, "pinyin": "suoluomenqundao", "value": "所罗门群岛 0677" },
      { "aleph": "smy", "continent": 4, "id": "+685", "length": 9, "pinyin": "samoya", "value": "萨摩亚 0685" },
      { "aleph": "shlnd", "continent": 5, "id": "+290", "length": 9, "pinyin": "shenghelenadao", "value": "圣赫勒拿岛 0290" },
      { "aleph": "sdmhplxb", "continent": 5, "id": "+239", "length": 9, "pinyin": "shengduomeihepulinxibi", "value": "圣多美和普林西比 0239" },
      { "aleph": "snje", "continent": 5, "id": "+221", "length": 9, "pinyin": "saineijiaer", "value": "塞内加尔 0221" },
      { "aleph": "sse", "continent": 5, "id": "+248", "length": 9, "pinyin": "saisheer", "value": "塞舌尔 0248" },
      { "aleph": "slla", "continent": 5, "id": "+232", "length": 9, "pinyin": "sailaliang", "value": "塞拉利昂 0232" },
      { "aleph": "sd", "continent": 5, "id": "+249", "length": 9, "pinyin": "sudan", "value": "苏丹 0249" },
      { "aleph": "swsl", "continent": 5, "id": "+268", "length": 9, "pinyin": "siweishilan", "value": "斯威士兰 0268" },
      { "aleph": "sml", "continent": 5, "id": "+252", "length": 9, "pinyin": "suomali", "value": "索马里 0252" },
    ],
    [
      { "aleph": "tg", "continent": 1, "id": "+66", "length": 9, "pinyin": "taiguo", "value": "泰国 0066" },
      { "aleph": "tjkst", "continent": 1, "id": "+992", "length": 9, "pinyin": "tajikesitan", "value": "塔吉克斯坦 0992" },
      { "aleph": "teq", "continent": 1, "id": "+90", "length": 9, "pinyin": "tuerqi", "value": "土耳其 0090" },
      { "aleph": "tkmst", "continent": 1, "id": "+993", "length": 9, "pinyin": "tukumansitan", "value": "土库曼斯坦 0993" },
      { "aleph": "tkshkksqd", "continent": 2, "id": "1649", "length": 9, "pinyin": "tekesihekaikesiqundao", "value": "特克斯和凯科斯群岛 1649" },
      { "aleph": "tlndhdbg", "continent": 2, "id": "1868", "length": 9, "pinyin": "telinidaheduobage", "value": "特立尼达和多巴哥 1868" },
      { "aleph": "tkl", "continent": 4, "id": "+690", "length": 9, "pinyin": "tuokelao", "value": "托克劳 0690" },
      { "aleph": "tj", "continent": 4, "id": "+676", "length": 9, "pinyin": "tangjia", "value": "汤加 0676" },
      { "aleph": "twl", "continent": 4, "id": "+688", "length": 9, "pinyin": "tuwalu", "value": "图瓦卢 0688" },
      { "aleph": "tsny", "continent": 5, "id": "+255", "length": 9, "pinyin": "tansangniya", "value": "坦桑尼亚 0255" },
      { "aleph": "tns", "continent": 5, "id": "+216", "length": 9, "pinyin": "tunisi", "value": "突尼斯 0216" },
    ],
    [
    ],
    [
    ],
    [
      { "aleph": "wl", "continent": 1, "id": "+673", "length": 9, "pinyin": "wenlai", "value": "文莱 0673" },
      { "aleph": "wzbkst", "continent": 1, "id": "+998", "length": 9, "pinyin": "wuzibiekesitan", "value": "乌兹别克斯坦 0998" },
      { "aleph": "wnrl", "continent": 2, "id": "+58", "length": 11, "pinyin": "weineiruila", "value": "委内瑞拉 0058" },
      { "aleph": "wdml", "continent": 2, "id": "+502", "length": 9, "pinyin": "weidimala", "value": "危地马拉 0502" },
      { "aleph": "wlg", "continent": 2, "id": "+598", "length": 9, "pinyin": "wulagui", "value": "乌拉圭 0598" },
      { "aleph": "wkl", "continent": 3, "id": "+380", "length": 9, "pinyin": "wukelan", "value": "乌克兰 0380" },
      { "aleph": "wnat", "continent": 4, "id": "+678", "length": 9, "pinyin": "wanuatu", "value": "瓦努阿图 0678" },
      { "aleph": "wlshftn", "continent": 4, "id": "+681", "length": 9, "pinyin": "walisihefutuna", "value": "瓦利斯和富图纳 0681" },
      { "aleph": "wgd", "continent": 5, "id": "+256", "length": 9, "pinyin": "wuganda", "value": "乌干达 0256" },
    ],
    [
      { "aleph": "xjp", "continent": 0, "id": "+65", "length": 8, "pinyin": "xinjiapo", "value": "新加坡 0065" },
      { "aleph": "xxl", "continent": 0, "id": "+64", "length": 10, "pinyin": "xinxilan", "value": "新西兰 0064" },
      { "aleph": "xly", "continent": 1, "id": "+963", "length": 9, "pinyin": "xuliya", "value": "叙利亚 0963" },
      { "aleph": "xl", "continent": 3, "id": "+30", "length": 9, "pinyin": "xila", "value": "希腊 0030" },
      { "aleph": "xyl", "continent": 3, "id": "+36", "length": 9, "pinyin": "xiongyali", "value": "匈牙利 0036" },
      { "aleph": "xby", "continent": 3, "id": "+34", "length": 9, "pinyin": "xibanya", "value": "西班牙 0034" },
      { "aleph": "xkldny", "continent": 4, "id": "+687", "length": 9, "pinyin": "xinkaliduoniya", "value": "新喀里多尼亚 0687" },
      { "aleph": "xshl", "continent": 5, "id": "+210", "length": 9, "pinyin": "xisahala", "value": "西撒哈拉 0210" },
    ],
    [
      { "aleph": "yd", "continent": 1, "id": "+91", "length": 10, "pinyin": "yindu", "value": "印度 0091" },
      { "aleph": "ydnxy", "continent": 1, "id": "+62", "length": 11, "pinyin": "yindunixiya", "value": "印度尼西亚 0062" },
      { "aleph": "yn", "continent": 1, "id": "+84", "length": 10, "pinyin": "yuenan", "value": "越南 0084" },
      { "aleph": "yl", "continent": 1, "id": "+98", "length": 9, "pinyin": "yilang", "value": "伊朗 0098" },
      { "aleph": "ylk", "continent": 1, "id": "+964", "length": 9, "pinyin": "yilake", "value": "伊拉克 0964" },
      { "aleph": "yd", "continent": 1, "id": "+962", "length": 9, "pinyin": "yuedan", "value": "约旦 0962" },
      { "aleph": "ymny", "continent": 1, "id": "+374", "length": 9, "pinyin": "yameiniya", "value": "亚美尼亚 0374" },
      { "aleph": "ysl", "continent": 1, "id": "+972", "length": 9, "pinyin": "yiselie", "value": "以色列 0972" },
      { "aleph": "ym", "continent": 1, "id": "+967", "length": 9, "pinyin": "yemen", "value": "也门 0967" },
      { "aleph": "ymj", "continent": 2, "id": "1876", "length": 9, "pinyin": "yamaijia", "value": "牙买加 1876" },
      { "aleph": "yswejqd", "continent": 2, "id": "1284", "length": 9, "pinyin": "yingshuweierjingqundao", "value": "英属维尔京群岛 1284" },
      { "aleph": "ydl", "continent": 3, "id": "+39", "length": 10, "pinyin": "yidali", "value": "意大利 0039" },
      { "aleph": "yg", "continent": 3, "id": "+44", "length": 10, "pinyin": "yingguo", "value": "英国 0044" },
    ],
    [
      { "aleph": "zg", "continent": 0, "id": "+86", "length": 11, "pinyin": "zhongguo", "value": "中国 0086" },
      { "aleph": "zgtw", "continent": 0, "id": "+886", "length": 9, "pinyin": "zhongguotaiwan", "value": "中国台湾 0886" },
      { "aleph": "zgxg", "continent": 0, "id": "+852", "length": 8, "pinyin": "zhongguoxianggang", "value": "中国香港 0852" },
      { "aleph": "zgam", "continent": 1, "id": "+853", "length": 8, "pinyin": "zhongguoaomen", "value": "中国澳门 0853" },
      { "aleph": "zl", "continent": 2, "id": "+56", "length": 9, "pinyin": "zhili", "value": "智利 0056" },
      { "aleph": "zf", "continent": 5, "id": "+236", "length": 9, "pinyin": "zhongfei", "value": "中非 0236" },
      { "aleph": "zd", "continent": 5, "id": "+235", "length": 9, "pinyin": "zhade", "value": "乍得 0235" },
      { "aleph": "zby", "continent": 5, "id": "+260", "length": 9, "pinyin": "zanbiya", "value": "赞比亚 0260" },
    ]
  ]
}
